# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZYJH8_bKGhg-oZedozPxpA8zKJzzYvt
"""

pip install pandas folium streamlit streamlit-folium

!pip install geopy

import pandas as pd
import folium
from geopy.geocoders import Nominatim

import pandas as pd

startups = [

    # --- Cultivated meat / Cellular Agriculture ---
    {
        "name": "Cellva",
        "category": "Cultivated meat/Cellular Agriculture",
        "lat": -30.0346,
        "lon": -51.2177,
        "city": "Porto Alegre"
    },
    {
        "name": "Núcleo Vitro",
        "category": "Cultivated meat/Cellular Agriculture",
        "lat": -30.0346,
        "lon": -51.2177,
        "city": "Porto Alegre"
    },
    {
        "name": "BiomeHub",
        "category": "Cultivated meat/Cellular Agriculture",
        "lat": -27.5954,
        "lon": -48.5480,
        "city": "Florianópolis"
    },
    {
        "name": "AlgaSul",
        "category": "Cultivated meat/Cellular Agriculture",
        "lat": -32.0350,
        "lon": -52.0986,
        "city": "Rio Grande"
    },
    {
        "name": "JBS Biotech Innovation Center",
        "category": "Cultivated meat/Cellular Agriculture",
        "lat": -27.5954,
        "lon": -48.5480,
        "city": "Florianópolis"
    },

    # --- Fermentation ---
    {
        "name": "Typcal",
        "category": "Fermentation",
        "lat": -23.5505,
        "lon": -46.6333,
        "city": "São Paulo"
    },
    {
        "name": "Future Cow",
        "category": "Fermentation",
        "lat": -21.1775,
        "lon": -47.8103,
        "city": "Ribeirão Preto"
    },

    # --- Plant-based ---
    {
        "name": "Fazenda Futuro",
        "category": "Plant-based",
        "lat": -22.5202,
        "lon": -44.0996,
        "city": "Volta Redonda"
    },
    {
        "name": "Superbom",
        "category": "Plant-based",
        "lat": -23.5505,
        "lon": -46.6333,
        "city": "São Paulo"
    },
    {
        "name": "NoMoo",
        "category": "Plant-based",
        "lat": -22.9068,
        "lon": -43.1729,
        "city": "Rio de Janeiro"
    },
    {
        "name": "Nude",
        "category": "Plant-based",
        "lat": -23.5505,
        "lon": -46.6333,
        "city": "São Paulo"
    },
    {
        "name": "The New (The New Butchers)",
        "category": "Plant-based",
        "lat": -23.5505,
        "lon": -46.6333,
        "city": "São Paulo"
    },
    {
        "name": "Beleaf",
        "category": "Plant-based",
        "lat": -23.5505,
        "lon": -46.6333,
        "city": "São Paulo"
    },
    {
        "name": "Vida Veg",
        "category": "Plant-based",
        "lat": -21.2450,
        "lon": -44.9990,
        "city": "Lavras"
    },
]

df = pd.DataFrame(startups)

CATEGORY_COLORS = {
    "Cultivated meat/Cellular Agriculture": "red",
    "Fermentation": "yellow",
    "Plant-based": "green"
}

def get_marker_color(category):
    return CATEGORY_COLORS.get(category, "blue")

import folium

cores = {"Plant-based": "green", "Fermentation": "blue", "Cultivated meat/Cellular Agriculture": "red"}

mapa = folium.Map(location=[-14.2350, -51.9253], zoom_start=4)

for _, row in df.iterrows():
    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=row["name"],
        icon=folium.Icon(color=cores.get(row["category"], "gray"))
    ).add_to(mapa)

mapa

mapa.save('startups_map.html')
print("Map saved to startups_map.html")